/*
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

import java.util.Arrays;

class Solution {
    public char findTheDifference1(String s, String t) {
        char[] l1 = new char[s.length()];
        char[] l2 = new char[t.length()];
        for(int i=0; i<s.length(); i++) {
            l1[i] = s.charAt(i);
        }
        for(int j=0; j<t.length(); j++) {
            l2[j] = t.charAt(j);
        }
        Arrays.sort(l1);
        Arrays.sort(l2);
        for(int i=0; i<s.length(); i++) {
            if(l1[i] != l2[i]) {
                return l2[i];
            }
        }
        return l2[t.length()-1];
    }

    public char findTheDifference2(String s, String t) {
        char sum_s = 'a';
        char sum_t = 'a';
        int i=0;
        for(; i<s.length(); i++) {
            sum_s += s.charAt(i);
            sum_t += t.charAt(i);
        }
        sum_t += t.charAt(i);
        return (char) (sum_t - sum_s);
    }
}